# KDE Breeze Port

## blurb: KDE Breeze - based on https://github.com/KDE/breeze

background                  #232627
foreground                  #fcfcfc

selection_background        #fcfcfc
selection_foreground        #232627

url_color                   #3daee9

active_tab_background       #fcfcfc
active_tab_foreground       #232627
inactive_tab_background     #232627
inactive_tab_foreground     #fcfcfc

color0                      #232627
color1                      #ed1515
color2                      #11d116
color3                      #f67400
color4                      #1d99f3
color5                      #9b59b6
color6                      #1abc9c
color7                      #fcfcfc

color8                      #7f8c8d
color9                      #c0392b
color10                     #1cdc9a
color11                     #fdbc4b
color12                     #3daee9
color13                     #8e44ad
color14                     #16a085
color15                     #ffffff

color16                     #31363b
color17                     #783228
color18                     #17a262
color19                     #b65619
color20                     #1b668f
color21                     #614a73
color22                     #186c60
color23                     #63686d